export const APPOINTMENT_REQUEST_CREATE_REQUEST = "APPOINTMENT_REQUEST_CREATE_REQUEST";
export const APPOINTMENT_REQUEST_CREATE_SUCCESS = "APPOINTMENT_REQUEST_CREATE_SUCCESS";
export const APPOINTMENT_REQUEST_CREATE_FAIL = "APPOINTMENT_REQUEST_CREATE_FAIL";
export const APPOINTMENT_REQUEST_CREATE_RESET = "APPOINTMENT_REQUEST_CREATE_RESET";

export const APPOINTMENT_REQUEST_DELETE_REQUEST = "APPOINTMENT_REQUEST_DELETE_REQUEST";
export const APPOINTMENT_REQUEST_DELETE_SUCCESS = "APPOINTMENT_REQUEST_DELETE_SUCCESS";
export const APPOINTMENT_REQUEST_DELETE_FAIL = "APPOINTMENT_REQUEST_DELETE_FAIL";

export const APPOINTMENT_REQUEST_DETAILS_REQUEST = "APPOINTMENT_REQUEST_DETAILS_REQUEST";
export const APPOINTMENT_REQUEST_DETAILS_SUCCESS = "APPOINTMENT_REQUEST_DETAILS_SUCCESS";
export const APPOINTMENT_REQUEST_DETAILS_FAIL = "APPOINTMENT_REQUEST_DETAILS_FAIL";

export const APPOINTMENT_REQUEST_PAY_REQUEST = "APPOINTMENT_REQUEST_PAY_REQUEST";
export const APPOINTMENT_REQUEST_PAY_SUCCESS = "APPOINTMENT_REQUEST_PAY_SUCCESS";
export const APPOINTMENT_REQUEST_PAY_FAIL = "APPOINTMENT_REQUEST_PAY_FAIL";
export const APPOINTMENT_REQUEST_PAY_RESET = "APPOINTMENT_REQUEST_PAY_RESET";

export const APPOINTMENT_REQUEST_LIST_REQUEST = "APPOINTMENT_REQUEST_LIST_REQUEST";
export const APPOINTMENT_REQUEST_LIST_SUCCESS = "APPOINTMENT_REQUEST_LIST_SUCCESS";
export const APPOINTMENT_REQUEST_LIST_FAIL = "APPOINTMENT_REQUEST_LIST_FAIL";

export const APPOINTMENT_REQUEST_UPDATE_REQUEST = "APPOINTMENT_REQUEST_UPDATE_REQUEST";
export const APPOINTMENT_REQUEST_UPDATE_SUCCESS = "APPOINTMENT_REQUEST_UPDATE_SUCCESS";
export const APPOINTMENT_REQUEST_UPDATE_FAIL = "APPOINTMENT_REQUEST_UPDATE_FAIL";
export const APPOINTMENT_REQUEST_UPDATE_RESET = "APPOINTMENT_REQUEST_UPDATE_RESET";
